[versions]
activity-compose = "1.12.4"
android-gradle = "9.0.1"
datastore = "1.2.0"
compose = "2026.02.00"
junit = "4.13.2"
kotlin = "2.3.10"
ktor = "3.4.0"
lifecycle = "2.10.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
compose = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
datastore = { module = "androidx.datastore:datastore", version.ref = "datastore" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
junit = { module = "junit:junit", version.ref = "junit" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
lifecycle = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
material3 = { module = "androidx.compose.material3:material3" }
material-icons = { module = "androidx.compose.material:material-icons-core" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }