[versions]
android-gradle = "9.0.0"
navigation = "2.9.6"
compose = "2026.01.00"
junit = "4.13.2"
kotlin = "2.3.0"
ktor = "3.3.3"

[libraries]
compose = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
junit = { module = "junit:junit", version.ref = "junit" }
ktor-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
material3 = { module = "androidx.compose.material3:material3" }
material-icons = { module = "androidx.compose.material:material-icons-core" }
navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigation"}

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }